version: 1
steps:
  - name: set-workdir-and-analyze
    shell: bash
    run: |
      set -euo pipefail
      cd booknest-mobile-app-40323-40332/booknest_mobile_frontend
      flutter pub get
      flutter analyze
