# This file configures the analyzer for the Flutter app.
# Uses Flutter recommended lints; customize as needed.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Examples:
    # prefer_single_quotes: true
    # avoid_print: false
