.PHONY: analyze test run pubget

# Ensure commands are executed from the Flutter app root (this directory).
analyze:
	flutter pub get
	flutter analyze

test:
	flutter test

run:
	flutter run

pubget:
	flutter pub get
