name: Flutter Analyze

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: booknest-mobile-app-40323-40332/booknest_mobile_frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze
